"""
FastAPI Server for Narrative Atlas RAG Queries.

This server exposes the NarrativeAtlas RAG functionality via an API endpoint.
"""

import os
import sys
import logging
from fastapi import FastAPI
from langserve import add_routes
from pydantic import BaseModel
import uvicorn
from dotenv import load_dotenv

# Load environment variables (e.g., OPENAI_API_KEY)
load_dotenv()

# Add the src directory to the path to enable imports
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), 'src')))

# Import local modules
try:
    from models.narrative_atlas import NarrativeAtlas
except ImportError:
    print("Error: Could not import NarrativeAtlas. Ensure it's in src/models/")
    sys.exit(1)

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger('NarrativeAtlasAPI')

# --- Configuration ---
# !!! IMPORTANT: Update this path if your NarrativeAtlas data is stored elsewhere !!!
NARRATIVE_ATLAS_STORAGE_PATH = "output/narrative_atlas_storage" 
# --- End Configuration ---

# --- Initialize Narrative Atlas ---
logger.info(f"Initializing NarrativeAtlas from: {NARRATIVE_ATLAS_STORAGE_PATH}")
try:
    if not os.path.exists(NARRATIVE_ATLAS_STORAGE_PATH):
        logger.warning(f"Storage path {NARRATIVE_ATLAS_STORAGE_PATH} not found. Atlas might be empty or initialization might fail.")
    
    atlas = NarrativeAtlas(storage_path=NARRATIVE_ATLAS_STORAGE_PATH)
    # Load existing data - crucial step!
    atlas.load() 
    logger.info("NarrativeAtlas loaded successfully.")
    
    # Log some stats if available
    if atlas.vector_store and hasattr(atlas.vector_store.index, 'ntotal'):
        logger.info(f"FAISS index contains {atlas.vector_store.index.ntotal} vectors.")
    logger.info(f"Loaded {len(atlas.node_id_to_doc_id)} node ID mappings.")
    
except FileNotFoundError:
     logger.error(f"Error: Could not load NarrativeAtlas. FAISS index or ID maps not found at {NARRATIVE_ATLAS_STORAGE_PATH}. Ensure data exists or run ingestion first.")
     # Depending on desired behavior, you might want to exit or proceed with an empty atlas
     # For now, we'll proceed, but queries will likely fail or return no context.
     # atlas = NarrativeAtlas(storage_path=NARRATIVE_ATLAS_STORAGE_PATH) # Create empty if needed
except Exception as e:
    logger.error(f"An unexpected error occurred during NarrativeAtlas initialization: {e}", exc_info=True)
    sys.exit(1)
# --- End Initialize Narrative Atlas ---


# --- FastAPI App Setup ---
app = FastAPI(
    title="Narrative Atlas RAG API",
    version="1.0",
    description="API for querying the Narrative Atlas using Retrieval-Augmented Generation.",
)

# --- Define RAG Chain/Function ---

# Placeholder for the actual RAG chain with LLM integration
# For now, it just returns the prompt generated by answer_query_with_context

class QueryInput(BaseModel):
    query: str
    k: int = 3 # Number of nodes to retrieve

class RagOutput(BaseModel):
    result: str # Will contain the prompt for now, later the LLM response

async def get_rag_prompt(input_data: QueryInput) -> RagOutput:
    """Retrieves context and generates the LLM prompt."""
    logger.info(f"Received query: '{input_data.query}', k={input_data.k}")
    try:
        prompt_or_message = atlas.answer_query_with_context(
            user_query=input_data.query, 
            k=input_data.k
        )
        logger.info(f"Generated prompt/message length: {len(prompt_or_message)}")
        return RagOutput(result=prompt_or_message)
    except Exception as e:
        logger.error(f"Error during RAG processing: {e}", exc_info=True)
        # Return a user-friendly error message
        return RagOutput(result=f"Error processing query: {e}")

# --- Add Routes ---
# Expose the RAG function using Langserve
add_routes(
    app,
    get_rag_prompt, # Pass the async function directly
    path="/narrative-rag",
    input_type=QueryInput, # Specify input Pydantic model
    output_type=RagOutput, # Specify output Pydantic model
    config_keys=["k"] # Allow configuring 'k' via API call
)

# Simple health check endpoint
@app.get("/health")
async def health():
    # Check if atlas seems loaded
    atlas_status = "loaded" if atlas and atlas.vector_store else "not loaded"
    index_size = -1
    if atlas and atlas.vector_store and hasattr(atlas.vector_store.index, 'ntotal'):
        index_size = atlas.vector_store.index.ntotal
        
    return {"status": "ok", "atlas_status": atlas_status, "index_size": index_size}

# --- Run Server ---
if __name__ == "__main__":
    logger.info("Starting Narrative Atlas API server...")
    # Make sure OPENAI_API_KEY is set if you intend to use OpenAI later
    if not os.getenv("OPENAI_API_KEY"):
         logger.warning("OPENAI_API_KEY environment variable not set. LLM features will not work.")
         
    uvicorn.run(app, host="0.0.0.0", port=8000) 